---
title: "tidy_data"
output: html_document
---

#libraries
```{r}

library(tidyverse)
library(janitor)
library(here)
library(countrycode)
library(vroom)


```

Capture fisheries production data
```{r}
#Sort the symbols in values out
## "..." = data unavailable (here taken as zero)
## " " = data not separately available (here taken as zero)
## "-" = nil or zero (make zero)
## "0 0" = more than zero but less than half the unit used (taken to be 0.25)
## F = FAO estimate from available sources of information


(capture_prod <- 
   read_csv(here("data", "raw_data", "fisheries_prod_raw.csv")) %>% 
   clean_names() %>% 
   rename(country = country_country,
          species = species_asfis_species,
          fishing_area = fishing_area_fao_major_fishing_area,
          unit = unit_unit) %>% 
   pivot_longer(names_to = "year", values_to = "value", -c(country, species, fishing_area, unit)) %>% 
   filter(!country %in% c("Totals - Number", "Totals - Tonnes - live weight")) %>% 
   mutate(year = gsub("x", "", year) %>% 
            as.numeric,
          flag = case_when(value == "..." ~ "No data",
                           value == " " ~ "Data not separately available",
                           value == "-" ~ "Nil or zero",
                           value == "0 0" ~ "0<x<0.5",
                           grepl(" F", value) ~ "estimate",
                           TRUE ~ "Reported"), 
          value = case_when(value %in% c("...", " ", "-") ~ "0",
                            value == "0 0" ~ "0.25",
                            grepl(" F", value) ~ gsub(" F", "", value),
                            TRUE ~ value) %>% 
            as.numeric)
)

#sorts country coding to deal with non-UTF characters that country code depends on
Encoding(capture_prod$country) <- "latin1" #deals with the non-UTF
capture_prod$country <- iconv(capture_prod$country, "latin1", "UTF-8",sub='')

capture_prod$iso3c <- countrycode(capture_prod$country, origin = "country.name", destination = "iso3c", warn=TRUE)
capture_prod$iso3c <- case_when(capture_prod$country == "Zanzibar" ~ "TZA",
                                TRUE ~ capture_prod$iso3c)


saveRDS(object = capture_prod, file = here("data", "tidy_data", "capture_production_tidy.rds"))


```


Aquaculture production data
```{r}

(aqua_prod_raw <- read_csv(here("data", "raw_data", "aqua-prod-raw.csv")) %>% 
  clean_names() %>% 
  rename(country= country_country,
         species = species_asfis_species,
         area = aquaculture_area_fao_major_fishing_area,
         environment = environment_environment)
)


#sorts country coding to deal with non-UTF characters that country code depends on
Encoding(aqua_prod_raw$country) <- "latin1" #deals with the non-UTF
aqua_prod_raw$country <- iconv(aqua_prod_raw$country, "latin1", "UTF-8",sub='')



aquaculture_prod <- aqua_prod_raw %>% 
  pivot_longer(names_to = "year", values_to = "value", -c(country, species, area, environment, unit)) %>% 
  mutate(iso_3c = countrycode(country, origin = "country.name", destination = "iso3c", warn = TRUE)) %>%
  mutate(iso_3c = case_when(country == "Zanzibar" ~ "TZA",
                            TRUE ~ iso_3c)) %>% 
    mutate(year = gsub("x", "", year) %>% 
              as.numeric,
           flag = case_when(value == "..." ~ "No data",
                           value == " " ~ "Data not separately available",
                           value == "-" ~ "Nil or zero",
                           value == "0 0" ~ "0<x<0.5",
                           grepl(" F", value) ~ "estimate",
                           TRUE ~ "Reported"),
           value = case_when(value %in% c("...", " ", "-") ~ "0",
                           value == "0 0" ~ "0.25",
                           grepl(" F", value) ~ gsub(" F", "", value),
                           TRUE ~ value) %>% 
              as.numeric) %>% 
   filter(country != "Totals")

  
saveRDS(object = aquaculture_prod, file = here("data", "tidy_data", "aquaculture_production_tidy.rds"))

```


Fish food balance data
```{r}

(fish_fbs_raw <- read_csv(here("data", "raw_data", "fish_FBS_1961-2017.csv")) %>% 
   clean_names()
)

#remove every other column from row 6

col_seq <- seq(from = 6, to = 118, by=2)

fish_fbs_raw <- fish_fbs_raw[, -col_seq]

(fish_fbs <- fish_fbs_raw %>% 
      pivot_longer(cols = -c(country_name, faostat_group_name, element_name, unit_name), names_to = "year", values_to = "value") %>%
      mutate(year = gsub("x", "", year))
)


saveRDS(object = fish_fbs, file = here("data", "tidy_data", "fish_fbs_tidy.rds"))

```


Fish trade data - volume, temporal
```{r}

col_seq <- seq(from = 7, to = 93, by=2) #remove every other column from the 7th

seafood_trade_raw <- read_csv(here("data", "raw_data", "fish_trade_volume_1976-2019.csv")) %>% 
   clean_names() %>% 
   select(-col_seq) %>% 
   filter(!reporting_country_name %in% c("Totals - Tonnes – net product weight", "FAO. 2021. Fishery and Aquaculture Statistics. Global Fish Trade - All partners aggregated 1976-2019 (FishstatJ). In: FAO Fisheries and Aquaculture Division [online]. Rome. Updated 2021. www.fao.org/fishery/statistics/software/fishstatj/en"))


seafood_trade_volume <- seafood_trade_raw %>% 
   pivot_longer(names_to = "year", values_to = "value", cols=-c(1:5)) %>% 
   mutate(year = gsub("x", "", year) %>% 
             as.numeric)

saveRDS(object = seafood_trade_volume, file = here("data", "tidy_data", "seafood_trade_volume_product_weight_1976-2019.rds"))
   


```


Fish trade data - value, temporal
```{r}

(seafood_value <- read_csv(here("data", "raw_data", "fish_trade_value_1976-2019.csv")) %>% 
   clean_names() %>% 
    select(-seq(from = 7, to = 93, by =2)) %>% 
 pivot_longer(cols=-c(1:5), names_to = "year", values_to = "value") %>% 
    mutate(year = gsub("x", "", year) %>% 
              as.numeric,
           value = value*1000,
           unit = "USD",
           unit_name = "Value")
)

saveRDS(object = seafood_value, file = here("data", "tidy_data", "seafood_trade_value_product_weight_1976-2019.rds"))

```
Fish trade - volume by trade partner in 2019
```{r}

seafood_trade_volume_2019 <- read_csv(here("data", "raw_data", "fish_trade_volume_by_partner_2019.csv")) %>% 
   clean_names() %>% 
   rename(value_2019 = x2019,
          flag = s) %>% 
   mutate(flag = case_when(flag == "E" ~ "estimate",
                           TRUE ~ "reported")) %>% 
   select(-unit_name)


saveRDS(object = seafood_trade_volume_2019, file = here("data", "tidy_data", "seafood_trade_volume_by_partner_2019.rds"))

```


