---
title: "Live equivalents conversion"
output: html_document
---

libraries

```{r}

library(tidyverse)
library(janitor)
library(here)

```


```{r}

hs_codes <- readRDS(file = here("data", "tidy_data", "cn_8_codes.rds")) %>% 
  mutate(cn_8 = substring(text = cn_8, first = 1, last=6)) %>% 
  group_by(cn_8) %>% 
  summarise(mean_cf = mean(cf),
            median_cf = median(cf))


seafood_trade_products <- readRDS(here("data", "tidy_data", "seafood_trade_volume_product_weight_by_partner_2019.rds")) %>% 
  filter(reporting_country_name == "Australia") |> 
  mutate(hs_code = stringr::str_replace(string = hs_code, pattern = "[[:punct:]]", replacement =  ""))



seafood_live_equivalents_2019 <- 
  seafood_trade_products %>% 
  left_join(y=hs_codes %>%  rename(hs_code = cn_8), by = c("hs_code")) %>% 
  mutate(value_LE_med_cf = if_else(median_cf==0,true = 0, false = value_2019*median_cf),
         value_LE_mean_cf = if_else(mean_cf==0,true = 0, false = value_2019*mean_cf)) %>% 
  distinct()



saveRDS(object = seafood_live_equivalents_2019, file = here("data", "tidy_data", "seafood_trade_volume_live_equivalent_by_partner_2019.rds"))


seafood_trade_volume_1976_2020 <- 
  readRDS(here("data", "tidy_data", "seafood_trade_volume_product_weight_1976_2020.rds")) %>% 
  filter(reporting_country_name == "Australia") |> 
  mutate(hs_code = stringr::str_replace(string = hs_code, pattern = "[[:punct:]]", replacement =  "")) |> 
  left_join(y=hs_codes %>%  rename(hs_code = cn_8), by = c("hs_code")) %>% 
  mutate(value_LE_med_cf = if_else(median_cf==0,true = 0, false = value*median_cf),
         value_LE_mean_cf = if_else(mean_cf==0,true = 0, false = value*mean_cf)) |> 
  filter(year!=2020)

saveRDS(object = seafood_trade_volume_1976_2020, file = here("data", "tidy_data", "seafood_trade_volume_live_equivalent_1976_2019.rds"))



#CODE JOIN FOR FAO CODES
# codes <- readRDS(here("data", "tidy_data", "fao_product_codes.rds")) 
# 
# seafood_products_codes <- seafood_trade_products %>% 
#   left_join(codes, by="commodity_name")
# 
# seafood_products_codes %>% 
#   group_by(reporting_country_name, commodity_name, partner_country_name, trade_flow_name, fao_code) %>% 
#   summarise(count = n())
# 
# 
# seafood_products_codes %>% 
#   filter(is.na(value_2019) )



seafood_live_equivalents %>% filter(partner_country_name=="Thailand")

seafood_trade_products %>% filter(partner_country_name=="Thailand" & trade_flow_name == "Imports")



readRDS(here("data", "tidy_data", "seafood_trade_volume_product_weight_1976-2019.rds")) %>% 
  filter(reporting_country_name == "Australia") |> 
  mutate(hs_code = stringr::str_replace(string = hs_code, pattern = "[[:punct:]]", replacement =  ""))




```

