---
title: "Australia's seafood supply gap"
output: html_document
---

#libraries
```{r}

libs <- c("tidyverse", "janitor", "here", "RColorBrewer", "ggpubr", "rnaturalearth", "zoo")

lapply(X= libs, FUN=library, character.only=TRUE)


```

Shapefiles
```{r}

bbox <- rnaturalearth::ne_download(scale=110, type = "wgs84_bounding_box",  category = "physical" , returnclass = "sf")

world_shp <- rnaturalearth::ne_countries(scale = 110, returnclass = "sf")

aus_shp <- world_shp %>% filter(iso_a3=="AUS")

```

Create map thumbnails
```{r}

(world_map <- ggplot()+
  geom_sf(data = sf::st_transform(bbox, crs = "ESRI:54009"), colour="grey50", fill=NA, size=0.1)+
  geom_sf(data = sf::st_transform(world_shp, crs = "ESRI:54009"), fill="grey50", colour=NA, size=0.1)+
   theme_void()
)


(aus_map <- ggplot()+
  geom_sf(data= sf::st_crop(x=aus_shp, y=c(xmin = 112.9082, xmax = 158.9589, ymin=-45, ymax=-10.05176)), fill="grey50", colour=NA)+
  theme_void()
)
```


Growing demands for fish over anything else

```{r}

fbs_aus <-  readRDS(here("data", "tidy_data", "food_balance_aus_1961-2013.rds"))

items_of_interest <- c( "Cereals - Excluding Beer", "Fruits - Excluding Wine",  "Starchy Roots" ,"Vegetables", "Fish, Seafood",   "Meat" , "Eggs", "Milk - Excluding Butter")


#total food supply first
fbs_aus_total <- fbs_aus %>% 
  filter(element == "Food") %>%
  filter(item %in% c(items_of_interest)) %>% 
  mutate(item = case_when(item %in% c("Fruits - Excluding Wine", "Vegetables") ~ "Fruits, Vegetables",
                          item == "Cereals - Excluding Beer" ~ "Cereals",
                          item == "Milk - Excluding Butter" ~ "Milk",
                          TRUE ~ item),
         value= value*1000, 
         unit="tonnes") %>% 
  group_by(item, unit, year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup() %>% 
  group_by(item) %>% 
  nest() %>% 
  mutate(rel_value = purrr::map(data, ~(.$value/.$value[1]))) %>% 
  unnest(cols = c(data, rel_value)) %>% 
  ungroup()


ggplot()+
  geom_line(data = fbs_aus_total,
            mapping = aes(x=year, y=rel_value, colour=item))


#per capita food supply probably better
fbs_aus_caput <- fbs_aus %>% 
  filter(element == "Food supply quantity (kg/capita/yr)") %>%
  filter(item %in% c(items_of_interest)) %>% 
  mutate(item = case_when(item %in% c("Fruits - Excluding Wine", "Vegetables") ~ "Fruits, Vegetables",
                          item == "Cereals - Excluding Beer" ~ "Cereals",
                          item == "Milk - Excluding Butter" ~ "Milk",
                          TRUE ~ item),
         value= value, 
         unit="tonnes") %>% 
  group_by(item, unit, year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup() %>% 
  group_by(item) %>% 
  nest() %>% 
  mutate(rel_value = purrr::map(data, ~(.$value/.$value[1]))) %>% 
  unnest(cols = c(data, rel_value)) %>% 
  ungroup() %>% 
  mutate(item = factor(item, levels = (c("Fish, Seafood", "Starchy Roots", "Fruits, Vegetables", "Meat", "Milk", "Cereals", "Eggs"))))







(relative_supply <- ggplot()+
  geom_line(data = fbs_aus_caput,
            mapping = aes(x=year, y=rel_value, colour=item)) +
  scale_color_manual(values = rev(colorRampPalette(brewer.pal(n=8, name = "GnBu"))(12)[3:12]))+
  scale_x_continuous(limits = c(1960,2026))+
  geom_text(data = fbs_aus_caput %>% filter(year ==2013),
            mapping = aes(x = 2013.5, y=rel_value, label=item), hjust=0, size=2)+
  theme_pubr()+
  theme(text = element_text(size=8),
        legend.text = element_text(size=6),
        legend.title = element_blank(),
        legend.position = "right",
        legend.key.width = unit(0.3, "cm"), 
        legend.key.height = unit(0.7, "cm"),
        legend.box.spacing = unit(-0.7, "cm"),
        legend.margin = margin(c(0,0,0,0), "cm"))+
  labs(y=bquote(Relative~per~capita~food~supply), x="Year")+
  guides(colour = FALSE)+
  annotation_custom(ggplotGrob(aus_map), xmin = 1960, xmax=1975, ymin=1.7, ymax=2.2)
)
ggsave(filename = here("explore", "cottrell_explore", "relative supply change.jpg"), device="jpg", dpi = 300, width = 9, height = 7, units = "cm")


```
Supplementary comparison of seafood and chicken
```{r}

fish_meats <- fbs_aus %>% 
  filter(element == "Food supply quantity (kg/capita/yr)") %>%
  filter(item %in% c("Fish, Seafood", "Poultry Meat", "Pigmeat", "Bovine Meat")) %>%
  group_by(item) %>% 
  nest() %>% 
  mutate(rel_value = map(data, ~(.$value/.$value[1]))) %>% 
  unnest(cols = c(data, rel_value))


  #plot
  ggplot()+
  geom_line(data = fish_meats, 
            mapping=aes(x=year, y=value, colour=item))+
  theme_pubr()+
  theme(text=element_text(size=8)) +
  scale_colour_manual(values = brewer.pal(n=9, name="Blues")[c(3, 5, 7, 9)])+
  scale_x_continuous(limits = c(1961, 2024))+
  geom_text(data= fish_meats %>% filter(year==2013),
            mapping = aes(x=2014, y=value, label = item), hjust=0, size=1.8)+
  guides(colour=FALSE)+
    labs(x="Year", y=bquote(Food~supply~(kg~capita^-1~yr^-1)))
  
  ggsave(filename = here("figures", "Supplementary figure - fish and meat consumption rates.jpg"), device="jpg", dpi = 600, width = 9, height=7, units = "cm")



```



Growing trade dependence

```{r}

fbs <- readRDS(file = here("data", "tidy_data", "fish_fbs_tidy.rds")) 

fbs_aus <- fbs %>% 
  filter(country_name=="Australia") %>% 
  group_by(element_name, year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup() %>% 
  mutate(year = year %>% as.numeric)


adj_fbs_aus <- 
  fbs_aus %>% filter(element_name %in% c("Production", "Food exports", "Stock variations", "Non-food uses", "Total food supply", "Food imports")) %>% 
  pivot_wider(names_from = element_name, values_from = value) %>% 
  mutate(`Domestic production` = Production-`Food exports`-(`Non-food uses`*0.5)+(`Stock variations`*0.5), #adj production by half of non food use and stock variations
         `Imports` = `Food imports`- (`Non-food uses`*0.5)+(`Stock variations`*0.5)) %>% #adj imports by half of non food uses and stock variations
  pivot_longer(names_to = "element_name", values_to = "value", cols = -year) %>% 
  select(element_name, year, value) 



#proportion of supply from imports for supplementary

(import_proportions_df <- 
  adj_fbs_aus %>% 
  filter(element_name %in% c("Domestic production", "Imports")) %>% 
  mutate(element_name = factor(element_name, levels = c("Imports", "Domestic production"))) %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(prop = purrr::map(data, ~(.$value/sum(.$value)))) %>% 
  unnest(cols=c(data, prop)) %>% 
  ungroup() %>% 
  arrange(element_name) %>% 
  group_by(element_name) %>% 
  nest() %>% 
  mutate(rolling_mean = map(data, ~(rollapplyr(data = .$prop,
                                               width = 5, 
                                               FUN = mean, 
                                               fill=NA)))) %>% 
  unnest(cols = c(data, rolling_mean))
)


```



Plot import proportins through time
```{r}
(import_proportions <- 
  ggplot(data = import_proportions_df)+
  geom_bar(mapping = aes(x = year, y= prop, fill=element_name), stat="identity", position="dodge")+
  geom_vline(xintercept = 1995, linetype=2, colour="black")+
  geom_line(aes(x=year, y=rolling_mean, colour=element_name), linetype=1)+
  scale_fill_manual(values = rev(brewer.pal(n=9, name = "Blues")[c(4,9)]))+
  scale_colour_manual(values = rev(brewer.pal(n=9, name = "YlOrRd")[c(6,9)]))+
  theme_pubr()+
  theme(text=element_text(size=8),
        legend.text = element_text(size=7),
        legend.title = element_text(size=7), 
        legend.position = "bottom",
        legend.background = element_rect(fill = "transparent"),
        legend.box.spacing = unit(0, "cm"),
        legend.key.size = unit(0.5, "cm"))+
  labs(x="Year", y="Proportion of seafood supply", fill="Source", colour="Five-year mean")+
  geom_text(x=1984, y = 0.74, label="WTO founded", size=3)+
  guides(fill = guide_legend(direction = "horizontal", title.position = "top", title.hjust = 0.5),
         colour = guide_legend(direction = "horizontal", title.position = "top", title.hjust = 0.5))+
  annotate("segment", x=1989, xend = 1994, y=0.74, yend=0.74, arrow = arrow(ends = "last", length = unit(0.3, "cm")))
)



ggsave(here("figures", "Supplementary figure - proportion of supply by source.jpg"), device = "jpg", dpi=600, width = 18, height=9, units = "cm")
```


Plot production and import supply trends
```{r}
(imports_production <- ggplot()+
  geom_area(data = adj_fbs_aus %>% 
              filter(element_name %in% c("Domestic production", "Imports")) %>% 
              mutate(element_name = factor(element_name, levels = c("Imports", "Domestic production"))),
             mapping = aes(x=year, y=value/1000, fill=element_name))+
    geom_line(data = adj_fbs_aus %>% filter(element_name %in% c("Total food supply")),
              mapping = aes(x=year, y=value/1000), col="black") +
    scale_fill_manual(values = brewer.pal(n=2, "Blues"))+
    theme_pubr()+
    theme(
          legend.position = c(0.25, 0.8),
          text = element_text(size=8),
          legend.text = element_text(size=7),
          legend.key.size = unit(0.5, "cm"))+
    labs(y= "Seafood supply (1000s tonnes, LWE)",x = "Year", fill="Source")+
    scale_y_continuous(labels = scales::comma)+
  geom_text(data = adj_fbs_aus %>% 
              filter(element_name %in% c("Domestic production", "Imports")) %>% 
              mutate(element_name = factor(element_name, levels = c("Imports", "Domestic production"))) %>% 
              left_join(import_proportions_df, by=c("element_name", "year", "value")) %>% 
              filter(year %in% c(1966, 1977, 1987, 1997, 2007, 2017)) %>%
              mutate(rolling_mean = round(rolling_mean*100, digits=1)) %>% 
              group_by(year) %>% 
              nest() %>% 
              mutate(total_value = map(data, ~(sum(.$value)))) %>%
              unnest(cols=c(data, total_value)) %>% 
              filter(element_name=="Imports"),
            mapping = aes(x=year, y=total_value/1000, label=rolling_mean), 
            size=1.8,
            nudge_y = -50)
  
  # annotation_custom(ggplotGrob(world_map), xmin = 1998, xmax=2016, ymin = 220, ymax=400)+
  # annotation_custom(ggplotGrob(aus_map), xmin = 2000, xmax=2015, ymin = 10, ymax=145)
  )

ggsave(here("explore", "cottrell_explore", "imports_v_production.jpg"), device="jpg", dpi=300, width=9, height=7, units="cm")
```




Export combined plot of fish relative to other foods and the source of seafood supply
```{r}
ggarrange(relative_supply,
          imports_production,
          nrow = 1,
          ncol=2, 
          labels = letters[1:2],
          font.label = list(size=10))

ggsave(here("figures", "Figure 1 - Australia's seafood supply gap_1.jpg"), device = "jpg", dpi=600, width = 18, height = 7, units = "cm")


ggarrange(
  ggarrange(relative_supply,
          imports_production,
          nrow = 1,
          ncol=2, 
          labels = letters[1:2],
          font.label = list(size=10)),
  
  import_proportions,
  nrow = 2, 
  ncol = 1,
  labels = c("", letters[3]),
  font.label = list(size=10),
  
  heights = c(8, 9)
)

ggsave(here("figures", "Figure 1 - Australia's seafood supply gap_2.jpg"), device = "jpg", dpi=600, width = 18, height = 17, units = "cm")


```


