---
title: "Social and ecological risks in trade"
output: html_document
---

```{r}

libs <- c("tidyverse", "here", "janitor", "countrycode", "ggrepel")

lapply(X=libs, FUN=library, character.only=TRUE)

```

Read in data
```{r}

import_totals <- readRDS(file = here("data", "tidy_data", "Aus_import_country_totals_live_equiv.rds")) %>% mutate(iso3c = countrycode(partner_country_name, origin = "country.name", destination = "iso3c", warn=TRUE))

ecosystem_viability_2020 <- readRDS(file=here("data", "tidy_data", "ecosystem_viability.rds")) %>% dplyr::select(-country) %>% 
  rename(ecosystem_viability = ECO.new)

slavery_index <- readRDS(file = here("data", "tidy_data", "gsi.rds")) %>% 
  mutate(iso3c = countrycode(sourcevar = country, origin = "country.name", destination = "iso3c", warn = TRUE)) %>% 
  dplyr::select(-country, -gsi_prev)

gov_effect_2020 <- readRDS(file = here("data", "tidy_data", "government_effectiveness.rds")) %>% 
  filter(year==2020) %>% 
  dplyr::select(-country_name, -year)


gov_effect_2020$gov_effect[gov_effect_2020$iso3c=="AUS"]

```

Shapefiles
```{r}

bbox <- rnaturalearth::ne_download(scale=110, type = "wgs84_bounding_box",  category = "physical" , returnclass = "sf")

world_shp <- rnaturalearth::ne_countries(scale = 110, returnclass = "sf")

aus_shp <- world_shp %>% filter(iso_a3=="AUS")

```

Create map thumbnails
```{r}

(aus_map <- ggplot()+
  geom_sf(data= sf::st_crop(x=aus_shp, y=c(xmin = 112.9082, xmax = 158.9589, ymin=-45, ymax=-10.05176)), fill=rev(brewer.pal(n=9, name = "YlGnBu"))[8], colour=NA)+
  theme_void()+
   annotate("text", x=135, y=-24, label= round(gov_effect_2020$gov_effect[gov_effect_2020$iso3c=="AUS"], digits = 2), size=2)
)
```


Join data for all dimensions
```{r}


all_metrics <- import_totals %>% 
  left_join(ecosystem_viability_2020, by="iso3c") %>% 
  left_join(slavery_index, by="iso3c") %>% 
  left_join(gov_effect_2020, by="iso3c") %>% 
  mutate(prop_le = value_le_median/sum(value_le_median) )

saveRDS(object = all_metrics, file = here("data", "tidy_data", "social_ecological_trade_metrics.rds"))

```


Plot 
```{r}

all_metrics <- readRDS(file = here("data", "tidy_data", "social_ecological_trade_metrics.rds")) %>% 
   mutate(partner_country_name = case_when(partner_country_name == "Taiwan Province of China" ~ "Taiwan",
                                          partner_country_name == "United States of America" ~ "USA",
                                          partner_country_name == "Korea, Republic of" ~ "Rep. Korea",
                                           partner_country_name == "Viet Nam" ~ "Vietnam",
                                          TRUE ~ partner_country_name)) 


ggplot()+
  geom_hline(yintercept = ecosystem_viability_2020 %>% filter(iso3c =="AUS") %>% .$ecosystem_viability, linetype=2, colour="grey70")+
  geom_vline(xintercept = slavery_index %>% filter(iso3c =="AUS") %>% .$gsi_vuln, linetype=2, colour="grey70")+
  geom_point(data =  all_metrics, 
              aes(x=gsi_vuln, y=ecosystem_viability, colour=gov_effect, size=prop_le))+
  geom_text_repel(data = all_metrics %>% slice(1:20), 
                  mapping= aes(x=gsi_vuln, y=ecosystem_viability, label=partner_country_name), 
                  box.padding = unit(0.5, "lines"),
                  # nudge_x = 1.5,
                  # nudge_y = 1,
                  position = "jitter",
                  min.segment.length = 0,
                  max.iter = 1e+6,
                  inherit.aes = FALSE,
                  segment.colour ="grey50",
                  segment.alpha = 0.5,
                  seed = 42,
                  size=2
                  )+
  scale_y_continuous(limits = c(10,80))+
  scale_x_continuous(limits = c(10,80))+
  theme_bw()+
  theme(text = element_text(size = 7),
        legend.text = element_text(size=7),
        legend.title = element_text(size = 7),
        panel.grid = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.key = element_rect(fill="transparent"))+
  scale_color_gradientn(colours = rev(brewer.pal(n=9, name = "YlGnBu")), na.value = "grey80")+
  #scale_colour_gradient2(low = "firebrick", mid = "pink", high = "blue", midpoint = 0, limits=c(-2.5,2.5))+
  scale_size_continuous(breaks = c(0.001, 0.01, 0.1, 0.2, 0.3))+
  coord_cartesian(xlim = c(10,80), clip="off")+
  #annotation_custom(ggplotGrob(aus_map), xmin = 96, xmax = 104, ymin = 33, ymax=42)+ by the legend
  annotation_custom(ggplotGrob(aus_map), xmin = 96, xmax = 104, ymin = 33, ymax=42)+

  labs(x="Vulnerability to slavery", y="Ecosystem viability", colour="Government effectiveness", size="Proportion of seafood imports")
  #geom_smooth(mapping = aes(x=gsi_vuln, y=ecosystem_viability), formula = y~s(x), method = "gam", level=0)
  
ggsave(filename = here("figures", "Figure 3- social-ecological tradeoffs.jpg"), device = "jpg", dpi=600, width = 16.5, height = 12, units = "cm")







```

