---
title: "Limitations in capture fisheries"
output: html_document
---


```{r}
libs <- c("tidyverse", "janitor", "here", "RColorBrewer", "ggpubr", "rnaturalearth", "zoo", "geojsonio", "sf", "rmapshaper", "mapmisc", "purrr", "ggthemes")

lapply(libs, library, character.only=TRUE)

``` 




#Old code - ignore. Insert new data and visualisations above.

Projections
```{r}

wgs_84 <- "EPSG:4326"

mollweide <- "ESRI:54009"

mollweide_pacific <- "+proj=moll +lon_0=150 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +towgs84=0,0,0"

gp_pacific <- "+proj=cea +lon_0=150 +lat_ts=45 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs "

```



Shapefiles
```{r}

bbox_shp <- rnaturalearth::ne_download(scale=50, type = "wgs84_bounding_box",  category = "physical" , returnclass = "sf")

world_shp <- rnaturalearth::ne_countries(scale = 50, returnclass = "sf") %>% rmapshaper::ms_simplify()



#create shapefile tools for pacific mollweide projection
offset <- 180 - 150

polygon <- st_polygon(x = list(rbind(c(-0.0001-offset, 90),
                                     c(0-offset, 90),
                                     c(0-offset, -90),
                                     c(-0.0001-offset, -90),
                                     c(-0.0001-offset, 90)))) %>%
  st_sfc() %>%
  st_set_crs(4326)


#world_shp_pacific <- world_shp %>% st_shift_longitude() %>% st_transform(crs = mollweide_pacific)

world_shp_pacific <- world_shp %>% st_difference(polygon) %>% st_transform(crs = mollweide_pacific)
#bbox_pacific <- bbox_shp %>% st_shift_longitude() %>% st_transform(crs = mollweide_pacific)


aus_shp <- world_shp %>% filter(iso_a3=="AUS")

aus_open_seas <- world_shp %>% filter(region_un=="Seven seas (open ocean)" | iso_a3=="AUS")

fao_areas <- download.file("http://www.fao.org/fishery/geoserver/fifao/ows?service=WFS&request=GetFeature&version=1.0.0&typeName=fifao:FAO_AREAS_CWP&outputFormat=json", dest="FAO.json")

fao_areas <- geojsonio::geojson_read("FAO.json", what = "sp") %>% sf::st_as_sf() %>% rmapshaper::ms_simplify()


```

Create map thumbnails
```{r}


(aus_map <- ggplot()+
  geom_sf(data=  sf::st_crop(aus_open_seas, c(xmin = 110, xmax=200, ymin = -42, ymax=-7)), fill="grey90", colour=NA)+

  theme_bw()+
   theme(panel.grid = element_blank())
)

unique(world_shp$region_un)

```

Read in fisheries data
```{r}

(capture_production_aus <- readRDS(here("data/tidy_data/capture_production_tidy.rds")) %>% 
  filter(iso3c =="AUS")
)

aus_fishing <- raster(here("data/spatial/aus_industrial_fishing.tif")) 
aus_fishing_pacific <- projectRaster(from = aus_fishing, crs = mollweide_pacific)


```



Explore data
```{r}
# unique(capture_production_aus$species)
# unique(capture_production_aus$fishing_area)


(fishing_areas_df <- 
  capture_production_aus %>% 
  filter(!grepl("Inland", fishing_area)) %>% 
  filter(year %in% c(2015, 2016, 2017)) %>% 
  group_by(fishing_area, year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup() %>% 
  group_by(fishing_area) %>% 
  summarise(value=mean(value)) %>% 
  arrange(-value) %>% 
    mutate(prop = value/sum(value))
)

(
marine_spp <- capture_production_aus %>% 
  filter(!grepl("Inland", fishing_area)) %>% 
  filter(year=="2017") %>% 
  group_by(species) %>% 
  summarise(value=sum(value)) %>% 
  arrange(-value)
  )
  
marine_totals <- capture_production_aus %>% 
  filter(!grepl("Inland", fishing_area)) %>% 
  group_by(year) %>% 
  summarise(value=sum(value))

top_10_marine_spp_totals <- capture_production_aus %>% 
  filter(!grepl("Inland", fishing_area)) %>% 
  group_by(species, year) %>% 
  summarise(value=sum(value)) %>% 
  filter(species %in% marine_spp$species[1:10])
  
other_marine_spp_totals <- capture_production_aus %>% 
  filter(!grepl("Inland", fishing_area)) %>% 
  group_by(species, year) %>% 
  summarise(value=sum(value)) %>% 
  filter(!species %in% marine_spp$species[1:10]) 

length(unique(other_marine_spp_totals$species)) #191 other species or species groups make up the surplus
```


Plot landings
```{r}
totals_for_plot <- 
  bind_rows(
    top_10_marine_spp_totals,
    
    other_marine_spp_totals %>% 
      group_by(year) %>% 
      summarise(value=sum(value)) %>% 
    mutate(species = "Other spp.")
)


species_levels <- c(marine_spp$species[1:10], "Other spp.")



(species_landings <- ggplot() +
  geom_area(data = totals_for_plot %>% 
              mutate(species = factor(species, levels = (species_levels))), 
            aes(x=year, y=value/1000, fill = species))+
    geom_vline(xintercept = 2007, linetype=2, colour="grey80", size=0.75)+
     #geom_line(data = marine_totals, aes(x=year, y=value/1000), colour="grey80", linetype=1)+
  scale_fill_manual(values = rev(colorRampPalette(brewer.pal(n=9, name = "PuBu"))(11)))+
    # scale_x_continuous(expand = c(0,0))+
    # scale_y_continuous(expand = c(0,10))+
    theme_pubr()+
    theme(panel.grid = element_blank(),
          legend.position = c(0.23, 0.74),
          legend.key.size = unit(0.21, "cm"),
          legend.key = element_rect(colour = NA, size=0.2, fill = "transparent"),
          legend.title = element_blank(),
          legend.text = element_text(size=6.5),
          text = element_text(size = 9),
          plot.margin = unit(c(0.2,0.6, 0.2,0.2), "cm"),
          # plot.background = element_rect(fill="transparent", colour=NA),
          # panel.background = element_rect(fill="transparent",),
          legend.background = element_rect(fill="transparent")
          )+
    labs(y="Landings (1000s tonnes)", x="Year")
)
  
ggsave(filename = here("explore/cottrell_explore/fisheries_aus_region_species.jpg"), device="jpg", dpi = 600,width = 9, height = 6,  units="cm")
```


Map with landings and fishing area proportions

```{r}

fao_areas_w_fishing <- fao_areas %>% filter(NAME_EN %in% c("Indian Ocean, Eastern", "Pacific, Southwest", "Pacific, Western Central",  "Indian Ocean, Antarctic")) %>% left_join(fishing_areas, by=c("NAME_EN" = "fishing_area")) 


#total global fisheries for Australia

aus_fishing_pacific_df <- aus_fishing_pacific %>% as("SpatialPixelsDataFrame") %>% data.frame()

(global_aus_fishing <- 
  ggplot()+
  geom_tile(data = aus_fishing_pacific_df, aes(x=x,y=y, fill=(aus_industrial_fishing+1)))+
  geom_sf(data= world_shp_pacific, fill="lemonchiffon2", colour="black", size=0.1)+
  scale_fill_gradientn(colours = brewer.pal(n=9, "BuPu"),
                       trans = "log10",
                       breaks = c(0, 1, 10, 100, 1000),
                       # labels = c("0", "0.001", "1.000", "1000")
  )+
  theme_pubr()+
  theme(panel.grid.minor = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_text(size=8.5),
        legend.text = element_text(size=8.5),
        legend.position = "bottom",
        legend.background = element_rect(fill="transparent"),
        legend.box.spacing = unit(0, "cm"),
        #plot.margin = unit(c(0.2,0.3,0.2,0.3), "cm")
        )+

  labs(fill="Landings (tonnes)")+
  guides(fill = guide_colorbar(barheight = unit(0.11, "cm"), title.position = "top", title.hjust = 0.5))
)
ggsave(here("explore/cottrell_explore/spatialised_landings_global.jpg"), width = 9, height = 6, units = "cm")


  #plot for just water surrounding australia

# aus_fishing_raster_blank <- raster(crs=wgs_84, extent(c(xmin = 70, xmax = 180, ymin=-60, ymax=18))) 
# 
# aus_fishing_aus <- crop(aus_fishing, aus_fishing_raster_blank)
# 
#   
# aus_fishing_aus_df <- aus_fishing_aus %>%  as("SpatialPixelsDataFrame") %>% data.frame()
# 
# 
# 
# aus_fishing_map <- 
#   ggplot()+
#   
#   geom_tile(data = aus_fishing_aus_df, aes(x=x,y=y, fill=(aus_industrial_fishing+1)))+
#    
#   geom_sf(data= sf::st_crop(aus_shp , c(xmin = 110, xmax=160, ymin = -62, ymax=-7)), fill="lemonchiffon2", colour="black", size=0.1)+
#   geom_sf(data= sf::st_crop(x=world_shp_2,  y=c(xmin = 70, xmax=180, ymin = -62, ymax=12)), colour="black", size=0.2)+
#   scale_fill_gradientn(colours = brewer.pal(n=9, "BuPu"),
#                        trans = "log10",
#                        # breaks = c(0, 0.001, 1.000, 1000),
#                        # labels = c("0", "0.001", "1.000", "1000")
#                        )+
#   scale_y_continuous(expand = c(0,0))+
#   scale_x_continuous(expand = c(0,0))+
#   coord_sf(crs = wgs_84)+
#   theme_bw()+
#   theme(panel.grid = element_blank(),
#         axis.title = element_blank(),
#         axis.text = element_blank(),
#         axis.ticks = element_blank(),
#         plot.margin = unit(c(0,-0.5,0,-0.5), "cm"),
#         text = element_text(size=8),
#         legend.box.spacing = unit(c(-0.2,0,0,0), "cm"),
#         legend.text = element_text(size=6),
#         legend.title = element_text(size=6),
#         legend.position = "bottom",
#         legend.background = element_rect(fill="transparent"))+
#   labs(fill="Landings (tonnes)")+
#   guides(fill = guide_colorbar(barheight = unit(0.13, "cm"), title.position = "top", title.hjust = 0.5))
# 

```

Combine temporal and spatial landings
```{r}
time_space_landings <- 
  ggarrange(species_landings,
          global_aus_fishing,
          labels = c("a", "b"),
          font.label = list(size=9),
          nrow = 1,
          ncol=2)


ggsave(here("explore/cottrell_explore/temporal_spatial_landings.jpg"), device = "jpg", dpi=600, height = 6, width = 18, units = "cm")
```




Early warning signs in current catch paradigm
```{r}

aus_fisheries <- 
  totals_for_plot %>% 
   group_by(year) %>% 
    summarise(value=sum(value)) %>%
    mutate(normalized_value = (value - mean(value))/sd(value),
           log10_value = log10(value),
           diff_value = c(0,diff(value)),
           gam_residuals= resid(mgcv::gam(value~s(year))))  
  


window <- c(0.3, 0.4,0.5, 0.6,0.7)

ews_variables <- function(this_window){
  
  assign(paste0("window_", this_window), 
         
         
         aus_fisheries %>% 
           mutate(Variance = rollapply(data = gam_residuals, 
                                width = this_window*length(gam_residuals), 
                                FUN = sd, 
                                align = "right", 
                                fill = NA, 
                                na.rm = T)) %>% 
    mutate(Mean = rollapply(data = gam_residuals, 
                            width = this_window*length(gam_residuals), 
                            FUN = mean, 
                            align = "right", 
                            fill = NA, 
                            na.rm = T)) %>%
    mutate(CV=Variance/Mean) %>%
    mutate(AR1 = rollapply(data = gam_residuals, 
                           width = this_window*length(gam_residuals), 
                           FUN = function(z,  na.rm = FALSE){
                             return(acf(z, plot=FALSE)$acf[2])
                           },  
                           align = "right", 
                           fill = NA, 
                           na.rm = T)) %>% 
    mutate(return_rate = rollapply(data=gam_residuals,
                                   width= this_window*length(gam_residuals),
                                   FUN = function(z, na.rm=FALSE){
                                     ar1 <- ar.ols(z,demean=FALSE, order.max = 1, aic = FALSE, intercept = FALSE)
                                     return(return_rate = 1/ar1$ar[1])
                                   },
                                   align = "right", 
                                   fill = NA, 
                                   na.rm = T)) %>% 
    mutate(kurtosis = rollapply(data=gam_residuals,
                                   width=this_window*length(gam_residuals),
                                   FUN = moments::kurtosis,
                                   align = "right", 
                                   fill = NA, 
                                   na.rm = T)) %>% 
    mutate(skewness = rollapply(data=gam_residuals,
                                   width=this_window*length(gam_residuals),
                                   FUN = moments::skewness,
                                   align = "right", 
                                   fill = NA, 
                                   na.rm = T)) %>% 
    mutate(Width = this_window)
    
    )
  
}


fisheries_ews <- map_df(window, ews_variables)



```



EWS plots
```{r}

(landings <- 
   ggplot(data= totals_for_plot %>% group_by(year) %>% summarise(value=sum(value)),
       aes(x=year)) +
  geom_line(aes(y=value), colour="black", size=1.1)+
   geom_line(aes(y=predict(mgcv::gam(value~s(year)))), size=0.6, colour="purple")+
    theme_pubr()+
    theme(
      text = element_text(size=9),
      axis.title.x = element_blank()
      #plot.margin = unit(c(t=0.5, r=0.1,b=0.1,l=0.1), "cm")
    )+
    geom_vline(xintercept = 2007, linetype=2, colour="grey80", size=0.75)+
    scale_y_continuous(breaks = c(0 ,0.5e+5, 1e+5, 1.5e+5,2e+5, 2.5e+5, 3e+5), labels=c("0", "50", "100", "150", "200", "250","300"), limits = c(0, 2.9e+5))+
    scale_x_continuous(breaks=c(1960,1980,2000,2020), labels = c("1960","1980","2000","2020"), limits = c(1950,2020))+
    labs(y=bquote(Tonnes~(10^3)))+
    #annotation_custom(fishing_img, xmin = 1950, 1960, ymin = 1.9e+5, ymax=2.9e+5)+
    annotate("text", x=1951, y=2.7e+5,label="Total landings", hjust=0, size=2.9)
)


(residuals <- ggplot(fisheries_ews %>% filter(Width==0.5),
       aes(x=year)) +
  geom_line(aes(y=gam_residuals), colour="lightblue", size=1.1)+
  # geom_line(aes(y=Mean), colour="#EA7580", size=1.1)+
  #geom_line(aes(y=predict(gam(Value~s(Year)))), size=0.6, colour="grey60")+
    theme_pubr()+
    theme(
      text = element_text(size=9),
      axis.title.x = element_blank()
      #plot.margin = unit(c(t=0.5, r=0.1,b=0.1,l=0.1), "cm")
      
      
    )+
    geom_hline(yintercept = 0, linetype=1, colour="grey90", size=0.75)+
    geom_vline(xintercept = 2007, linetype=2, colour="grey80", size=0.75)+
    scale_y_continuous(breaks = c(-20e+3 ,0, 20e+3, 40e+3), labels=c("-20", "0", "20", "40"))+
    scale_x_continuous(breaks=c(1960,1980,2000,2020), labels = c("1960","1980","2000","2020"), limits = c(1950,2020))+
    labs(y=bquote(Tonnes~(10^3)))+
    #annotation_custom(fishing_img, xmin = 1950, 1960, ymin = 1.9e+5, ymax=2.9e+5)+
   annotate("text", x=1951, y=39e+3,label="GAM residuals", hjust=0, size=2.9)

)


(landings_residuals <- ggarrange(landings, residuals, 
          labels = c("c", "d"),
          font.label = list(size=9),
          ncol = 2,
          nrow = 1))

vars <- ggplot(data=fisheries_ews, aes(x=year, y=Variance))+
    geom_line()+
    facet_grid(.~Width)+
    theme_pubr()+
      theme(
        text = element_text(size=9),
        axis.title.x = element_blank()
      )+
      geom_vline(xintercept = 2007, linetype=2, colour="grey80", size=0.75)+
      scale_y_continuous(breaks = c(8e+3 ,10e+3, 12e+3, 14e+3,16e+3), labels=c("8", "10", "12", "14", "16"))+
      scale_x_continuous(breaks=c(1960,1980,2000,2020), labels = c("1960","1980","2000","2020"), limits = c(1950,2020))+
      labs(y=bquote(Variance~(Tx10^3)))
    
  
  ar1 <- ggplot(data=fisheries_ews, aes(x=year, y=AR1))+
    geom_line()+
    facet_grid(.~Width)+
    theme_pubr()+
      theme(
        text = element_text(size=9),
        axis.title.x = element_blank()
      )+
      geom_vline(xintercept = 2007, linetype=2, colour="grey80", size=0.75)+
      #scale_y_continuous(breaks = c(8e+3 ,10e+3, 12e+3, 14e+3,16e+3), labels=c("8", "10", "12", "14", "16"))+
      scale_x_continuous(breaks=c(1960,1980,2000,2020), labels = c("1960","1980","2000","2020"), limits = c(1950,2020))+
      labs(y="AR1", x="Year")
  
  
  
  comp_fisheries <- fisheries_ews %>% 
    drop_na() %>% 
    group_by(Width) %>% 
    nest() %>% 
    mutate(Normalised_variance = map(data, ~((.$Variance-mean(.$Variance))/sd(.$Variance))),
           Normalised_AR = map(data, ~((.$AR1-mean(.$AR1))/sd(.$AR1)))) %>% 
    unnest() %>% 
    mutate(Composite_index = Normalised_variance+Normalised_AR)
  
  
   comp_index <- ggplot(data=comp_fisheries, aes(x=year, y=Composite_index))+
    geom_line()+
    facet_grid(.~Width)+
    theme_pubr()+
      theme(
        text = element_text(size=9),
        axis.title.x = element_blank()
      )+
      geom_vline(xintercept = 2007, linetype=2, colour="grey80", size=0.75)+
      #scale_y_continuous(breaks = c(8e+3 ,10e+3, 12e+3, 14e+3,16e+3), labels=c("8", "10", "12", "14", "16"))+
      scale_x_continuous(breaks=c(1960,1980,2000,2020), labels = c("1960","1980","2000","2020"), limits = c(1950,2020))+
      labs(y=bquote(Composite~index))
   
   
(ews_analysis <- 
  ggarrange(landings_residuals, vars,ar1, comp_index, 
           nrow=4, ncol=1,
           labels = c("", "e", "f", "g"),
           font.label = list(size=9),
           heights = c(1,0.75,0.75,0.75))
)
```


combine mapped time series landings and ews plots
```{r}

ggarrange(time_space_landings,
          ews_analysis,
          ncol = 1,
          nrow = 2,
          heights = c(1,3))



ggsave(here("figures/Figure 3 - landings through time and space - ews.jpg"), dpi=600, device = "jpg", height = 24, width = 17, units = "cm")
ggsave(here("figures/Figure 3 - landings through time and space - ews.pdf"), dpi=600, device = "pdf", height = 24, width = 17, units = "cm")

```

