---
title: "Sentiment analysis around aquaculture"
output: html_document
---

libraries
```{r}

library(tidyverse)
library(here)
library(stringr)
library(rvest)
library(sf)
library(rmapshaper)
library(scatterpie)
library(ggnewscale)

source(here("src/fxs.R"))

```



Sentiment analysis 2019
```{r}
#LATEST SEARCH ACROSS ALL SECTORS 22/07/19


#search terms "(aquaculture OR fish farm) <STATE> Australia"


#tasmania
tasmania <- read_html("https://news.google.com/search?q=(aquaculture%20OR%20fish%20farm)%20tasmania%20australia&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  tasmania %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")


tas_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "Tasmania", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              }))
                            )


#queensland

queensland <- read_html("https://news.google.com/search?q=(aquaculture%20OR%20fish%20farm)%20queensland%20australia&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  queensland %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

qld_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "Queensland", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))



#south australia

SA <- read_html("https://news.google.com/search?q=(aquaculture%20OR%20fish%20farm)%20south%20australia&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  SA %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

SA_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                           State = "South Australia", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))



#Western australia

WA <- read_html("https://news.google.com/search?q=(aquaculture%20OR%20fish%20farm)%20western%20australia&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  WA %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

WA_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                           State = "Western Australia", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))


#NSW


NSW <- read_html("https://news.google.com/search?q=(aquaculture%20OR%20fish%20farm)%20new%20south%20wales%20australia&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  NSW %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

NSW_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "New South Wales", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))



VIC <- read_html("https://news.google.com/search?q=(aquaculture%20OR%20fish%20farm)%20victoria%20australia&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  NSW %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

VIC_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "Victoria", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))




NT <- read_html("https://news.google.com/search?q=(aquaculture%20OR%20fish%20farm)%20northern%20territory%20australia&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  NT %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

NT_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                           State = "Northern Territory", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))


ACT <- read_html("https://news.google.com/search?q=(aquaculture%20OR%20fish%20farm)%20australian%20capital%20territory%20australia&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  ACT %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

ACT_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "Australian Capital Territory", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))


aquaculture_headlines <- 
  bind_rows(tas_headlines, qld_headlines, SA_headlines, VIC_headlines, NSW_headlines, NT_headlines, WA_headlines, ACT_headlines) %>% 
  mutate(System = "Aquaculture", Sentiment_1="", Sentiment_2="") %>% 
  select(System, State, Headline, Sentiment_1, Sentiment_2, Metadata) %>% 
  write_csv("Aquaculture headlines.csv")



```


Sentiment analysis 2022

Google news searches using e.g. aquaculture AND ("Queensland" OR QLD)
```{r}
#tasmania
tasmania <- read_html("https://news.google.com/search?q=aquaculture%20AND%20(tasmania%20OR%20TAS)&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  tasmania %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")


tas_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "Tasmania", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              }))
                            )


#queensland

queensland <- read_html("https://news.google.com/search?q=aquaculture%20AND%20(queensland%20OR%20QLD)&hl=en-AU&gl=AU&ceid=AU%3Aenn") 

headlines <- 
  queensland %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

qld_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "Queensland", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))



#south australia

SA <- read_html("https://news.google.com/search?q=aquaculture%20AND%20(%22South%20Australia%22%20OR%20SA)&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  SA %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

SA_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                           State = "South Australia", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))



#Western australia

WA <- read_html("https://news.google.com/search?q=aquaculture%20AND%20(%22Western%20Australia%22%20OR%20WA)&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  WA %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

WA_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                           State = "Western Australia", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))


#NSW


NSW <- read_html("https://news.google.com/search?q=aquaculture%20AND%20(%22New%20South%20Wales%22%20OR%20NSW)&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  NSW %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

NSW_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "New South Wales", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))



VIC <- read_html("https://news.google.com/search?q=aquaculture%20AND%20(%22Victoria%22%20OR%20VIC)&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  NSW %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

VIC_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "Victoria", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))




NT <- read_html("https://news.google.com/search?q=aquaculture%20AND%20(%22Northern%20Territory%22%20OR%20NT)&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  NT %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

NT_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                           State = "Northern Territory", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))


ACT <- read_html("https://news.google.com/search?q=aquaculture%20AND%20(%22Australian%20Capital%20Territory%22%20OR%20ACT)&hl=en-AU&gl=AU&ceid=AU%3Aen") 

headlines <- 
  ACT %>% 
  html_nodes("article") %>%
  html_text("span") %>%
  str_split("(?<=[a-z0-9!?\\.])(?=[A-Z])")
  

ACT_headlines <- tibble(Headline = unlist(lapply(headlines, '[[', 1)), 
                            State = "Australian Capital Territory", 
                            Metadata= unlist(lapply(headlines, function(list_element){
                                length <- length(list_element)
                                metadata <- paste(list_element[2:length], collapse = "")
                                return(metadata)
                              })))


aquaculture_headlines <- 
  bind_rows(tas_headlines, qld_headlines, SA_headlines, VIC_headlines, NSW_headlines, NT_headlines, WA_headlines, ACT_headlines) %>% 
  mutate(System = "Aquaculture", Sentiment_1="", Sentiment_2="") %>% 
  select(System, State, Headline, Sentiment_1, Sentiment_2, Metadata) %>% 
  write_csv(here("data/tidy_data/aquaculture_headlines_2022.csv"))



```


Import agreement results

```{r}

initial_agreemnet <- read_csv(here("data/raw_data/combined_sentiment.csv"))


nrow(initial_agreemnet %>% filter(agreement_1_2==TRUE))/nrow(initial_agreemnet) # ~75% agreement in first round



nrow(initial_agreemnet %>% filter((sentiment_1 == "Positive" & sentiment_2=="Negative") | (sentiment_1 == "Negative" & sentiment_2=="Positive")))/ nrow(initial_agreemnet)*100 # 0.26% of headline where opposite polarity (and it was the same headline)



```

Import agreed sentiment, fill in agreement for pre agreed, and summarise by state
```{r}

agreed_sentiment <- readRDS(here("data/tidy_data/combined_sentiment_agreed.rds")) %>% 
  mutate(agreement = case_when(is.na(agreement) ~ sentiment_1,
                                      sentiment_1 == sentiment_2 ~ sentiment_1,
                                      TRUE ~ agreement)) %>% 
  drop_na(agreement)


headline_relevance <- 553/782 #i.e. the proportion of non NA

(summarised_sentiment <- agreed_sentiment %>% 
  group_by(state, agreement) %>% 
  summarise(value = n()) %>% 
  ungroup() %>% 
  group_by(state) %>% 
  nest() %>% 
  mutate(total = purrr::map(data, ~(sum(.$value)))) %>% 
  unnest(c(data, total)) %>% 
  ungroup()
)


```


Map aquaculture production to states

```{r}

aus_state_aqua <- readRDS(here("data/tidy_data/state_aquaculture_production_tidy.rds")) %>% 
  mutate(state = case_when(state == "NSW" ~ "New South Wales", 
                           state == "VIC" ~ "Victoria", 
                           state == "QLD" ~ "Queensland", 
                           state == "SA" ~ "South Australia", 
                           state == "WA" ~ "Western Australia", 
                           state == "TAS" ~ "Tasmania", 
                           state == "NT" ~ "Northern Territory",
                           state == "ACT" ~ "Australian Capital Territory"))


state_totals <- aus_state_aqua %>% filter(species!= "Total" & year %in% c(2018)) %>% 
  group_by(state) %>% 
  summarise(quantity = sum(quantity, na.rm = TRUE))

state_shp <- st_read(here("data/spatial/STE_2021_AUST_SHP/STE_2021_AUST_GDA94.shp")) %>%
  st_set_precision(100) %>% 
  filter(!STE_NAME21 %in% c("Other Territories", "Outside Australia") ) %>% 
  left_join(state_totals, by = c("STE_NAME21" = "state")) %>% 
  mutate(lon = map_dbl(geometry, ~st_point_on_surface(.x)[[1]]),
         lat = map_dbl(geometry, ~st_point_on_surface(.x)[[2]])) %>% 
  mutate(offset = case_when(STE_NAME21 == "Tasmania" ~ 5,
                            STE_NAME21 == "Australian Capital Territory" ~ 4,
                            TRUE ~ 0),
         lon_adj = lon + offset)


st_crs(state_shp)

pie_centroids <- 
  tibble(state = state_shp$STE_NAME21, lon =  state_shp$lon_adj, lat = state_shp$lat) %>% 
  left_join(summarised_sentiment, by = "state") %>% 
  mutate(value = as.numeric(value),
         rel_total = total/min(total)) 


pie_segments <- 
  tibble(lon = state_shp %>% slice(c(6,8)) %>% pull(lon), lat = state_shp %>% slice(c(6,8)) %>% pull(lat), lon_adj = state_shp %>% slice(c(6,8)) %>% pull(lon_adj)) #only for ACT and TAS


crd <-  
crd$clip <- "off"

  ggplot()+
    geom_sf(data = state_shp, aes(fill = quantity+1), colour="grey30")
    scale_fill_gradientn(colours = RColorBrewer::brewer.pal(n = 5, name = "BuPu"),
                         trans = "log10",
                         na.value = "white")+
    labs(fill="Production (MT)")+
    geom_segment(data = pie_segments,  aes(x = lon, xend = lon_adj, y = lat, yend = lat), lineend = "round")+
    new_scale_fill()+
  geom_scatterpie(data = pie_centroids, aes(x=lon, y=lat, group = state, r=rel_total), long_format = TRUE, cols = "agreement", size=0.1)+
    geom_scatterpie_legend(radius = pie_centroids$rel_total, x = 161, y = -38.5, n = 10, labeller = function(x) min(pie_centroids$total)*x)+
    scale_fill_manual(values = c("firebrick", "grey80", "dodgerblue"))+
    labs(fill="Headline sentiment")+
        theme_void()+
    theme(legend.title = element_text(size = 10),
      legend.text = element_text(size=10),
      legend.position = c(0.95, 0.6))+
    annotate("text", x = 158.5, y = -34.5, label = "No. headlines", hjust =0, size=3.5)
    
  
ggsave(filename = here("figures/Figure 4 - sentiment and production.jpg"), device = "jpg", dpi = 600, width = 18, height = 12, units = "cm")

```

