---
title: "national_production"
author: "Rosa Mar Dominguez"
date: "25/07/2022"
output:
  html_document: default
  word_document: default
  pdf_document: default
---


#libraries
```{r}

library(tidyverse)
library(janitor)
library(here)
library(countrycode)
library(vroom)
library(ggplot2)
library(patchwork)
library(ggpubr)
library(RColorBrewer)

```


```{r}

(cap_aus <- readRDS(here("data", "tidy_data", "capture_production_tidy.rds")) %>% 
  select(- c("country", "unit")) %>% 
   mutate(type = "wild-caught"))


(aqu_aus <- readRDS(here("data", "tidy_data", "aquaculture_production_tidy.rds")) %>% 
    filter(country == "Australia") %>% 
    select(- c("country", "unit")) %>% 
    mutate(type = "farmed"))

(aqu_state <- readRDS(here("data", "tidy_data", "state_aquaculture_production_tidy.rds")))

aqu_aus_2 <- aqu_aus %>% 
  filter(value >0 )

ggplot(aqu_aus_2, aes(x = as.numeric(year), y = value, colour = species)) + 
  geom_line()


# calculate the proportion that each species contributes to total production

(aqu_aus_tot <- aqu_aus %>% 
  group_by(year) %>% 
  summarise(t_aqu_production = sum(value)) %>% 
    ungroup())


(aqu_aus_prop <- aqu_aus %>% 
  left_join(aqu_aus_tot, by = c("year" = "year")) %>% 
  group_by(species, year) %>% 
  mutate(prop = (sum(value)/t_aqu_production)*100) %>% 
    ungroup()) 

#Salmon, and tuna shrimp proportion

sal_tu_sh <- aqu_aus %>% 
  filter(grepl(c("salmon|Salmon|Tuna|tuna|Shrimp|shrimp"), species)) %>% 
  mutate(group = case_when(species %in% c("Atlantic salmon", "Chinook(=Spring=King) salmon") ~ "Salmon", 
                         species == "Southern bluefin tuna" ~ "Tuna", 
                         TRUE ~ "Shrimp")) %>% 
  group_by(year, group) %>% 
  summarise(production = sum(value)) %>% 
  ungroup() %>% 
  left_join(aqu_aus_tot, by = "year") %>% 
  mutate(prop = production*100/t_aqu_production) %>% 
  unique()

recent <- sal_tu_sh %>% 
  filter(year == "2020")

 # ggplot(aqu_aus_prop, aes(x = year, y = species)) + 
#   geom_bar(stat = "identity", aes(fill = prop))

# % of aquaculture production per species through time  
ggplot(aqu_aus_prop, aes(x = year, y = prop)) + 
  geom_line(aes(colour = species))

# % of farmed vs capture to total production 
aqu_aus1 <- aqu_aus %>% 
  select(species, year, value, type) 

palette = c("#4292C6", "#9ECAE1")


total_production <- cap_aus %>% 
  select(-c("fishing_area", "fishing_area_code", "isscaap_group")) %>% 
  rbind(aqu_aus1, by = "year") %>% 
  mutate(year = as.numeric(year)) %>% 
  drop_na() %>% 
  group_by(year) %>% 
  mutate(value = as.numeric(value)) %>% 
  summarise(total_prod = sum(value), species, year, type, value) %>% 
  ungroup() %>% 
  group_by(type, year) %>% 
  summarise(y_value = sum(value), total_prod) %>% 
  ungroup() %>% 
  unique()%>% 
  mutate(type = factor(type, levels = c("farmed", "wild-caught")))

prop_production <- total_production %>% 
  filter(type == "farmed") %>% 
  group_by(year) %>% 
  summarise(prop = (y_value/total_prod)*100, y_value, type) %>% 
  ungroup() %>% 
  filter(year %in% (c(seq(from= 1950, to = 2017, by = 10), "2017"))) #%>%
  # mutate(prop_aqu = (100-prop))
  
# (p_test <- ggplot(total_production %>% filter(year %in% 1950:2017),aes(x = year, y  = y_value, colour = type)) + 
#     geom_line() +
#     geom_smooth() + 
#     geom_line(mapping = aes(x = year, y = total_prod), colour = "black") + 
#     scale_x_continuous(limits = c(1950, 2019)) +
#     theme_pubr()+
#     theme(legend.position = c(0.25, 0.8),
#           plot.title = element_text(hjust = 0.5, size = 15),
#           text = element_text(size=12),
#           legend.text = element_text(size=9),
#           legend.key.size = unit(0.7, "cm"))+
#     labs(title = "Australian Seafood \nProduction System", y= "Seafood production (1000s tonnes, LWE)",x = "Year", colour="Source")+
#     scale_y_continuous(labels = scales::comma)+
#   geom_text(data = prop_production, mapping = aes(x=year, y=y_value/1000, label=round(prop)), 
#             size=3, nudge_y = 4) ) 

(production <- ggplot(total_production %>% filter(year %in% 1950:2017)) + 
   geom_area(aes(x = year, y = y_value/1000, fill = factor(type, levels = c("wild-caught", "farmed")))) + 
    geom_line(data = total_production %>% filter(year %in% 1950:2017),
              mapping = aes(x=year, y=total_prod/1000), col="black") +
    scale_fill_manual(values =  palette) +                     #brewer.pal(n=2, "Blues"))+
    scale_x_continuous(limits = c(1950, 2019)) +
    theme_pubr()+
    theme(legend.position = c(0.25, 0.8),
          plot.title = element_text(hjust = 0.5, size = 15),
          text = element_text(size=12),
          legend.text = element_text(size=9),
          legend.key.size = unit(0.7, "cm"))+
    labs(title = "Australian Seafood \nProduction System", y= "Seafood production (1000s tonnes, LWE)",x = "Year", fill="Source")+
    scale_y_continuous(labels = scales::comma)+
  geom_text(data = prop_production, mapping = aes(x=year, y=y_value/1000, label=round(prop)), 
            size=3, nudge_y = -1) 
  )

# (prop_line <- ggplot(total_production %>% filter(year %in% 1950:2017),aes(x = year, y  = y_value, colour = type)) + 
#     geom_line() +
#     #geom_smooth() + 
#     geom_line(mapping = aes(x = year, y = total_prod), colour = "black") + 
#     scale_x_continuous(limits = c(1950, 2019)) +
#   #geom_text(data = prop_production, mapping = aes(x=year, y=y_value, label=round(prop)), 
#    #         size=3, nudge_y = 10) +
#     theme_pubr()+
#     theme(legend.position = c(0.25, 0.8),
#           plot.title = element_text(hjust = 0.5, size = 15),
#           text = element_text(size=15),
#           legend.text = element_text(size=15),
#           legend.key.size = unit(0.7, "cm"))+
#     labs(title = "Australian Seafood \nProduction System", y= "Seafood production (1000s tonnes, LWE)",x = "Year", colour="Source")+
#     scale_y_continuous(labels = scales::comma)) 

# 
# display.brewer.pal(n = 8, name = "Blues")
# brewer.pal(n = 8, name = "Blues")

```




```{r sust stocks} 
sust_cap <- read.csv(here("data", "tidy_data", "fishery_stock_status.csv"), header = T)
GNBlupal = c("#08589E", "#1E79B2", "#3496C3", "#4AAFD1", "#66C0CA", "#83CFC1")

(sust_stocks <- ggplot(sust_cap, aes(x = year, y = prop*100, fill = status)) +
  geom_bar(stat = "identity") + 
    scale_fill_manual(values = GNBlupal) + 
    guides(fill = guide_legend(title = "Sustainability status")) + 
    theme_pubr()+
    theme(text = element_text(size=12),
          plot.title = element_text(size = 15, hjust = 0.5),
        legend.text = element_text(size=12),
        legend.title = element_blank(),
        legend.position = "right",
        legend.key.width = unit(0.3, "cm"), 
        legend.key.height = unit(0.7, "cm"),
        legend.box.spacing = unit(-0.7, "cm"))+    #,
        #legend.margin = margin(c(0,0,0,0), "cm"))+
  labs(y="Number of stocks (%)", x="Year")+
  guides(colour = FALSE) + 
    ggtitle("Sustainability of Australian \n Fisheries stocks")
  )  #+ 



glimpse(sust_cap)
```


```{r aqua data proportion fed vs unfed}

(aqu_dat <- aqu_aus %>% 
   mutate(fed_unfed = case_when(species %in% c("Australian mussel", "Sydney cupped oyster", "Sea mussels nei", "Southern Australia scallop", "Cupped oysters nei", "Flat and cupped oysters nei", "Pacific cupped oyster", "Flat oysters nei") ~ "unfed", 
                                TRUE ~ "fed")) %>% 
   group_by(year, fed_unfed) %>% 
   summarise(y_value = sum(value)) %>% 
   ungroup())
  

(prop_aqu <- aqu_dat %>% 
  group_by(year) %>% 
  summarise(total_value = sum(y_value), fed_unfed, y_value) %>%
  summarise(prop = (y_value/total_value)*100, y_value, fed_unfed, total_value)  %>% 
  ungroup() %>% 
  filter(year %in% (c(seq(from= 1950, to = 2017, by = 10), "2017"))))

(total_prod <- aqu_dat %>% 
    filter(year %in% 1950:2017) %>% 
  group_by(year) %>% 
  summarise(total_value = sum(y_value)) %>% 
    ungroup())
  
palette = c("#4292C6", "#9ECAE1")

(fed_unfed_aqua <- ggplot(aqu_dat %>% filter(year %in% 1950:2017)) + 
   geom_area(aes(x = year, y = y_value/1000, fill = factor(fed_unfed, levels = c("fed", "unfed")))) + 
   geom_line(data = total_prod, mapping = aes (x=year, y = total_value/1000), col  = "black") + 
   scale_fill_manual(values =  palette) +                     #brewer.pal(n=2, "Blues"))+
    scale_x_continuous(limits = c(1950, 2019)) +
    theme_pubr()+
    theme(legend.position = c(0.25, 0.8),
          plot.title = element_text(hjust = 0.5, size = 15),
          text = element_text(size=12),
          legend.text = element_text(size=9),
          legend.key.size = unit(0.7, "cm"))+
    labs(title = "Aquaculture production", y= "Aquaculture production (1000s tonnes, LWE)",x = "Year", fill="Fed/unfed")+
   # scale_y_continuous(labels = scales::comma)+
  geom_text(data = prop_aqu %>% filter(fed_unfed == "unfed"), mapping = aes(x=year, y=y_value/1000, label=round(prop)), 
            size=3, nudge_y = 3.5) 
  )
  
  
```



```{r eFCRs}
aqu_aus <- readRDS(here("data", "tidy_data", "aquaculture_production_tidy.rds")) %>% 
   filter(country == "Australia", 
          value > 0)


(aqu_aus_2 <- aqu_aus %>% 
    select(- c("country", "unit")) %>% 
    filter(!isscaap_group %in% c("Oysters", "Crabs, sea-spiders", "Mussels", "Scallops, pectens", "Miscellaneous aquatic invertebrates", "Miscellaneous marine molluscs", "Tunas, bonitos, billfishes", "Abalones, winkles, conchs"))) ## check tuna FCR apparently super super high; Naylor and Burke 2005 has FCR for finfishes at 3.84 in 2002
#Feed conversion ratios (FCR) are generally high around 15–20:1 for large specimens and 10–15:1 for smaller fish.  As a result only a small fraction (5 percent) ofthe total energy input is used for body growth (Korsmeyer and Dewars, 2001).
aqu_aus_3 <- aqu_aus_2 %>% 
    mutate(Taxa = case_when(grepl("Freshwater fishes", isscaap_group) ~ "FW fishes",
                            grepl("Barramundi", species) ~ "FW fishes",
                             grepl("salmon", species) ~ "Salmons",
                             grepl("trout", species) ~ "Trouts",
                             grepl("Freshwater crustaceans", isscaap_group) ~ "FW crustaceans ",
                             grepl("Marine fishes", species) ~ "Marine fishes ",
                             grepl("Finfishes", species) ~ "Marine fishes ",
                             grepl("marine crustaceans", species) ~ "Shrimps",
                             grepl("Shrimps", isscaap_group) ~ "Shrimps", 
                             grepl("eels", isscaap_group) ~ "Eels",
                             grepl("Miscellaneous freshwater fishes", isscaap_group) ~ "FW fishes", 
                          TRUE ~ "NA")) 


(eFCRs <-read.csv(here("data", "tidy_data", "eFCRs.csv")))
  
aqu_prod_eFCR <- aqu_aus_3 %>%
 left_join(eFCRs, by = c("Taxa", "year" = "Year")) 

# could try to make a figure with two y axis, on the left production by taxa per year (x), and on the right FCR

prod_FCR <- aqu_prod_eFCR %>% 
  group_by(Taxa, year) %>% 
  reframe(production = sum(value), eFCR, species, Taxa) %>% 
  drop_na(Taxa) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(aveFCR = mean(eFCR)) %>% 
  filter(! Taxa == "NA") %>% 
  ungroup()

#top eFCR 
tp_eFCR <- prod_FCR %>% 
  filter(year == "2015") %>% 
  select(Taxa, eFCR) %>% 
  unique() %>% 
  arrange(desc(eFCR))
# % of total production per eFCR group
eFCR_prop <- aqu_aus %>% mutate(Taxa = case_when(grepl("Freshwater fishes", isscaap_group) ~ "FW fishes",
                            grepl("Barramundi", species) ~ "FW fishes",
                             grepl("salmon", species) ~ "Salmons",
                             grepl("trout", species) ~ "Trouts",
                             grepl("Freshwater crustaceans", isscaap_group) ~ "FW crustaceans",
                             grepl("Marine fishes", species) ~ "Marine fishes ",
                             grepl("Finfishes", species) ~ "Marine fishes ",
                             grepl("marine crustaceans", species) ~ "Shrimps",
                             grepl("Shrimps", isscaap_group) ~ "Shrimps", 
                             grepl("eels", isscaap_group) ~ "Eels",
                             grepl("Miscellaneous freshwater fishes", isscaap_group) ~ "FW fishes", 
                          TRUE ~ isscaap_group)) %>% 
  select(-c("country", "fishing_area", "isscaap_group", "species", "fishing_area_code", "environment")) %>% 
  left_join(aqu_total_prod, by = "year") %>% 
  group_by(year, Taxa) %>% 
  reframe(production = sum(value), total_production) %>% 
  mutate(prop = production*100/total_production) %>% 
  unique()
  
eFCR_prop %>% filter(Taxa == "FW fishes")

display.brewer.pal(n = 5, name = "Blues")
palette= c(brewer.pal(n=5, "Blues"), "#83CFC1", "#66C0CA")
  GNBlupal
(eFCR_plot <- ggplot(prod_FCR %>% arrange(desc(eFCR))) + 
  geom_line( aes(x = year, y = eFCR, color= Taxa), size = 1) + 
  scale_color_manual(values =  palette) +                     #brewer.pal(n=2, "Blues"))+
    scale_x_continuous(limits = c(1994, 2012)) +
    theme_pubr()+
    theme(legend.position = "right",
          plot.title = element_text(hjust = 0.5, size = 15),
          text = element_text(size=12),
          legend.text = element_text(size=9),
          legend.key.size = unit(0.7, "cm"))+
    labs(title = "eFCR", y= "eFCR through time",x = "Year", color="Taxa group"))#+
   # scale_y_continuous(labels = scales::comma)+
  # geom_text(data = prop_aqu %>% filter(fed_unfed == "unfed"), mapping = aes(x=year, y=y_value, label=round(prop)), 
  #           size=3, nudge_y = 1.5) 

#average eFCR through time
av <- aqu_prod_eFCR %>%
  filter(!is.na(eFCR)) %>%
  group_by(year) %>% 
  summarise(av_eFCR = mean(eFCR))
  
  
  
# what % of the total aquaculture production does this fig cover?
 # all sp production, get total per year
aqu_total_prod <- aqu_aus %>%
  select(year, value) %>% 
  group_by(year) %>% 
  reframe(total_production = sum(value), year) %>% 
  ungroup() %>% 
  mutate(type = "total") %>% 
  unique()

FCR_total_prod <- aqu_prod_eFCR %>% 
  select(year, value) %>% 
  group_by(year) %>% 
  reframe(total_production_FCR = sum(value), year) %>% 
  mutate(type = "FCR") %>% 
  unique()

ggplot() + 
  geom_line(data = aqu_total_prod, aes(x = year, y = total_production)) +
  geom_line(data = FCR_total_prod, aes(x = year, y = total_production_FCR))


#calculate %%
(FCR_prop_total <- aqu_total_prod %>%  full_join(FCR_total_prod, by = "year") %>% 
  mutate(prop = total_production_FCR*100/total_production) %>% 
  select(year, prop) %>% 
  filter(!is.na(prop)) %>% 
    unique())

summary(FCR_prop_total)

ggplot(FCR_prop_total, aes(x = year, y = prop)) + 
  geom_line()


```


```{r Join sustainability and production figures}

(production + sust_stocks) / (fed_unfed_aqua + plot_spacer() + eFCR_plot) + plot_layout(nrow = 2)


#ggsave(filename = here("figures", "Australian Seafood Production (Draft Version!).jpg"), device="jpg", dpi = 600, width = 30, height=17, units = "cm")
```

``` {r}
(aqu_dat <- aqu_aus %>% 
  group_by(environment, year) %>% 
  summarise(env_value = sum(value), species, year,value) %>% 
  ungroup() %>% 
  group_by(species, year) %>% 
  summarise(y_value = sum(value), environment, env_value) %>% 
  ungroup() %>% 
    mutate(species = replace(species, str_detect(species, "oyster"), "oysters")))

(top <- aqu_dat%>% 
  slice_max(y_value, prop = 0.05))

summary(as.factor(top$species))

(aqu_top <- aqu_dat %>% 
  select(- c("environment", "env_value")) %>% 
  mutate(species = case_when(species %in% top$species ~ species, 
                            TRUE ~ "other")) %>% 
    group_by(species, year) %>% 
    summarise(value = sum(y_value)) %>% 
    ungroup())

(aqu_top_prop <- aqu_top %>% 
  group_by(year) %>% 
  summarise(total_prod_y = sum(value), species, value) %>% 
  ungroup() %>% 
    mutate(prop = (value/total_prod_y) *100))


(p1_sp <- ggplot(aqu_top) + 
  geom_line(aes(x = year, y = value, colour = species)))

(p2_env <- ggplot(aqu_dat) + 
  geom_line(aes(x = year, y = env_value, colour = environment)))

p3_prop_prod <- ggplot(aqu_top_prop) + 
  geom_line(aes(x = year, y  = prop, colour = species))

p1_sp + p3_prop_prod + plot_layout(guides = "collect")

```

